/*
 * HmAnthropicClaudeWeb v 1.1.1.3
 *
 * Copyright (c) 2025 Akitsugu Komiyama
 * under the MIT License
 */


hidemaruversion "9.39.99";

jsmode  @"WebView2\HmAnthropicClaudeWeb";

js {

// ------------- 会話エンジンの設定項目 -------------

const baseUrl = "https://claude.ai";

const renderPaneCustomParam = {
    place: "rightside",            // leftside | rightside | upside | downside
    size: 900,                     // 左や右の配置の時は、横幅のこと。上や下の配置の時は縦幅のこと。
                                   // Claudeのサイトに限っては、900以上の幅があることが必要。450なども指定した場合でも一瞬は幅が広くなる。
};

const isOneAtTimeAIRenderPane = 1; // AI関連のレンダリング枠は(他の種類のAIも含め)１つだけにする。(複数起動しそうになると、前のものが閉じる）

// --------------------------------------------------

const renderPaneTargetName = "HmAnthropicClaudeWeb";
    
const currentMacroDirectory = currentmacrodirectory();

const script = hidemaru.loadTextFile(currentMacroDirectory + "\\HmConvAIWeb.js");
eval(script);

function returnMinimumWindowSize() {
    if (renderPaneCustomParam.size < 900) {
        return {size:900};
    }
    
    return {};
}

const newConvBaseUrl = `${baseUrl}/new`; // 新ウィンドウ時のURL

// Claude は１回目だけ https://claude.ai/new で、2回目以降は https://claude.ai/chat と別URLになる珍しいパターン
// 最低サイズがある程度ないと、Claudeは入力欄(input)に自動的に焦点が合わない。
function firstParamDecorator(baseUrl, text) {
    return { ...{ url: newConvBaseUrl }, ...returnMinimumWindowSize() };
}

// 最低サイズがある程度ないと、Claudeは入力欄(input)に自動的に焦点が合わない。
// ２回目以降に、Claudeの返答等を選択した状態で質問した時の挙動が不安感があるので、リフレッシュもしておく。
function secondParamDecorator(baseUrl, text) {
    // browserpanecommand({target:"_each", "refresh":1});
    return returnMinimumWindowSize();
}

function onPrevKeySendDecorator() {
    try {
        const url = browserpanecommand({target:"_each", get:"url"});
        if (url != newConvBaseUrl) {
            com.SendShiftEscSlashDelSync();
        }
    } catch(e) {
    }
}

doMain();

}
